apiVersion: v1
kind: Pod
metadata:
  name: ha-nginx-pod-init-1
spec:
  containers:
  - name: ha-nginx-c-1
    image: nginx:1.10.1
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: ha-nginx-pod-init-2
spec:
  containers:
  - name: ha-nginx-c-1
    image: nginx:1.10.1
    ports:
    - containerPort: 80