apiVersion: v1
kind: Pod
metadata:
  name: ha-resource-quota-failure-pod
spec:
  containers:
  - name: ha-resource-quota-failure-pod-c-1
    image: nginx:1.10.1
    resources:
      limits:
        memory: "1.1Gi"
        cpu: "1100m"
      requests:
        memory: "600Mi"
        cpu: "600m"