apiVersion: v1
kind: Pod
metadata:
  name: ha-pod-affinity-pod
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: topology.kubernetes.io/region
            operator: In
            values:
            - us-central1
            - us-central1-b
        topologyKey: topology.kubernetes.io/zone
  containers:
  - name: ha-pod-affinity-c-1
    image: registry.k8s.io/pause:2.0