apiVersion: apps/v1
kind: Deployment
metadata:
  name: ha-frontend-service-pod
spec:
  selector:
    matchLabels:
      serv: frontend
  replicas: 2
  template:
    metadata:
      labels:
        serv: frontend
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: serv
                operator: In
                values:
                - frontend
            topologyKey: "kubernetes.io/hostname"
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: serv
                operator: In
                values:
                - backend
            topologyKey: "kubernetes.io/hostname"			
      containers:
      - name: ha-frontend-c-1
        image: nginx:1.10.1