apiVersion: v1
kind: Pod
metadata:
  name: ha-requests-limits-pod
spec:
  containers:
  - name: ha-requests-limits-pod-c-1
    image: nginx:1.10.1
    command: [ "/bin/sh", "-c", "touch /tmp/readiness; sleep 180; rm -f /tmp/readiness; sleep 180; touch /tmp/readiness; sleep 180;" ]
    resources:
      limits:
        cpu: "500m"
        memory: "700Mi"
      requests:
        cpu: "500m"
        memory: "700Mi"