apiVersion: v1
kind: LimitRange
metadata:
  name: ha-limit-range-all
spec:
  limits:
  - default:
      memory: 800Mi
      cpu: "800m"
    defaultRequest:
      memory: 600Mi
      cpu: "600m"
    max:
      cpu: "1500m"
      memory: 1500Mi
    min:
      cpu: "100m"
      memory: 100Mi
    type: Container