apiVersion: v1
kind: Service
metadata:
  name: ha-service-multi-port
spec:
  selector:
    aname: ha-app1
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8081