apiVersion: v1
kind: LimitRange
metadata:
  name: ha-limit-range-min-max
spec:
  limits:
  - max:
      cpu: "500m"
      memory: 500Mi
    min:
      cpu: "100m"
      memory: 100Mi
    type: Container