apiVersion: v1
kind: LimitRange
metadata:
  name: ha-limit-range-defaults
spec:
  limits:
  - default:
      memory: 800Mi
      cpu: "800m"
    defaultRequest:
      memory: 600Mi
      cpu: "600m"
    type: Container