apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ha-ingress-simple-http
spec:
  defaultBackend:
    service:
      name: service1
      port:
        number: 7070
  rules:
  - http:
      paths:
      - path: /test1
        pathType: Prefix
        backend:
          service:
            name: service2
            port:
              number: 8080