apiVersion: batch/v1
kind: Job
metadata:
  name: ha-nginx-job-activedeadlineseconds
spec:
  template:
    spec:
      containers:
      - name: ha-nginx-job-activedeadlineseconds-c-1
        image: nginx:1.10.1
        command:
         - "/bin/bash"
         - "-c"
         - "date; sleep 10; date;"
      restartPolicy: Never
  backoffLimit: 3
  activeDeadlineSeconds: 5