apiVersion: v1
kind: Pod
metadata:
  name: ha-liveness-tcp-socket-pod
spec:
  containers:
[...]
    livenessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 120
      periodSeconds: 30
[...]