apiVersion: v1
clusters:
- cluster:
   certificate-authority: /home/hagrawal7777/.minikube/ca.crt
   server: https://192.168.0.231:8443
  name: minikube
contexts:
- context:
   cluster: minikube
   namespace: default
   user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
   client-certificate: /home/hagrawal7777/.minikube/profiles/client.crt
   client-key: /home/hagrawal7777/.minikube/profiles/client.key