apiVersion: v1
kind: PersistentVolume
metadata:
  name: ha-persistent-volume
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 300Mi
  csi:
    driver: pd.csi.storage.xxx.io
    fsType: ext4
    volumeHandle: projects/ha-persistent-volume
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard-rwo
  volumeMode: Filesystem